name: Build and test

on:
  push:
    branches:
      - main

jobs:

  deploy:
  
      runs-on: ubuntu-latest
        
      steps: 

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: project-1-400619
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true
      
      - name: Set Kubectl Context
        run: gcloud container clusters get-credentials product-prod --zone us-central1 --project project-1-400619 

      - name: Configure docker for GCP
        run: gcloud auth configure-docker gcr.io

      - name: Deploy to GKE
        run: |
          docker pull gcr.io/project-1-400619/product:${{ github.run_number }}
          kubectl apply -f deployment.yaml
          
      - name: Create LoadBalancer Service
        run: kubectl apply -f service.yaml
